"""add durable financial lifecycle

Revision ID: 888e939179cd
Revises: 
Create Date: 2026-09-01 06:01:17.740642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '888e939179cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('external_account_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'external_account_id', name='uq_broker_account_external')
    )
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('ledger_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('order_intent_id', sa.String(length=36), nullable=True),
    sa.Column('broker_order_id', sa.String(length=36), nullable=True),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_events_broker_order_id'), 'ledger_events', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_correlation_id'), 'ledger_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_event_type'), 'ledger_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ledger_events_order_intent_id'), 'ledger_events', ['order_intent_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_position_id'), 'ledger_events', ['position_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_signal_id'), 'ledger_events', ['signal_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_strategy_id'), 'ledger_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_ledger_events_timestamp'), 'ledger_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ledger_events_user_id'), 'ledger_events', ['user_id'], unique=False)
    op.create_table('trading_signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'RISK_REJECTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXPIRED', 'ORDER_CREATED', 'EXECUTED', 'CANCELLED', 'FAILED', name='signalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_signals_correlation_id'), 'trading_signals', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_strategy_id'), 'trading_signals', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_trading_signals_user_id'), 'trading_signals', ['user_id'], unique=False)
    op.create_table('financial_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('broker_account_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('broker_position_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_CLOSED', 'CLOSED', 'LIQUIDATED', 'UNKNOWN', 'RECONCILIATION_REQUIRED', name='positionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fees', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id', 'broker_position_id', name='uq_position_external')
    )
    op.create_index(op.f('ix_financial_positions_broker_account_id'), 'financial_positions', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_financial_positions_signal_id'), 'financial_positions', ['signal_id'], unique=False)
    op.create_index(op.f('ix_financial_positions_strategy_id'), 'financial_positions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_financial_positions_user_id'), 'financial_positions', ['user_id'], unique=False)
    op.create_index('ix_position_user_status', 'financial_positions', ['user_id', 'status'], unique=False)
    op.create_table('order_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('broker_account_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('risk_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('risk_percent', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTING', 'SUBMITTED', 'ACKNOWLEDGED', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'FAILED', 'SUBMISSION_UNKNOWN', 'RECONCILIATION_REQUIRED', name='orderintentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index(op.f('ix_order_intents_broker_account_id'), 'order_intents', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_order_intents_correlation_id'), 'order_intents', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_order_intents_signal_id'), 'order_intents', ['signal_id'], unique=False)
    op.create_index(op.f('ix_order_intents_strategy_id'), 'order_intents', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_order_intents_user_id'), 'order_intents', ['user_id'], unique=False)
    op.create_table('trade_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', 'APPROVE_REDUCED', 'EXPIRED', name='approvaldecision', native_enum=False, length=32), nullable=False),
    sa.Column('approved_size_multiplier', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('telegram_message_id', sa.String(length=128), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['trading_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_approvals_signal_id'), 'trade_approvals', ['signal_id'], unique=False)
    op.create_index(op.f('ix_trade_approvals_user_id'), 'trade_approvals', ['user_id'], unique=False)
    op.create_table('broker_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_intent_id', sa.String(length=36), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=128), nullable=False),
    sa.Column('client_order_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_intent_id'], ['order_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker', 'broker_order_id', name='uq_broker_order_external')
    )
    op.create_index(op.f('ix_broker_orders_client_order_id'), 'broker_orders', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_order_intent_id'), 'broker_orders', ['order_intent_id'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('broker_order_id', sa.String(length=36), nullable=False),
    sa.Column('broker_execution_id', sa.String(length=128), nullable=False),
    sa.Column('broker_trade_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission_asset', sa.String(length=32), nullable=True),
    sa.Column('fee', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_order_id'], ['broker_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_id', 'broker_execution_id', name='uq_execution_external')
    )
    op.create_index(op.f('ix_executions_broker_order_id'), 'executions', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_executions_user_id'), 'executions', ['user_id'], unique=False)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("""
            CREATE FUNCTION reject_ledger_event_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'ledger_events is append-only';
            END;
            $$ LANGUAGE plpgsql
        """)
        op.execute("""
            CREATE TRIGGER ledger_events_append_only
            BEFORE UPDATE OR DELETE ON ledger_events
            FOR EACH ROW EXECUTE FUNCTION reject_ledger_event_mutation()
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER ledger_events_append_only ON ledger_events")
        op.execute("DROP FUNCTION reject_ledger_event_mutation()")
    op.drop_index(op.f('ix_executions_user_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_broker_order_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_broker_orders_order_intent_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_client_order_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    op.drop_index(op.f('ix_trade_approvals_user_id'), table_name='trade_approvals')
    op.drop_index(op.f('ix_trade_approvals_signal_id'), table_name='trade_approvals')
    op.drop_table('trade_approvals')
    op.drop_index(op.f('ix_order_intents_user_id'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_strategy_id'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_signal_id'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_correlation_id'), table_name='order_intents')
    op.drop_index(op.f('ix_order_intents_broker_account_id'), table_name='order_intents')
    op.drop_table('order_intents')
    op.drop_index('ix_position_user_status', table_name='financial_positions')
    op.drop_index(op.f('ix_financial_positions_user_id'), table_name='financial_positions')
    op.drop_index(op.f('ix_financial_positions_strategy_id'), table_name='financial_positions')
    op.drop_index(op.f('ix_financial_positions_signal_id'), table_name='financial_positions')
    op.drop_index(op.f('ix_financial_positions_broker_account_id'), table_name='financial_positions')
    op.drop_table('financial_positions')
    op.drop_index(op.f('ix_trading_signals_user_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_strategy_id'), table_name='trading_signals')
    op.drop_index(op.f('ix_trading_signals_correlation_id'), table_name='trading_signals')
    op.drop_table('trading_signals')
    op.drop_index(op.f('ix_ledger_events_user_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_timestamp'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_strategy_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_signal_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_position_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_order_intent_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_event_type'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_correlation_id'), table_name='ledger_events')
    op.drop_index(op.f('ix_ledger_events_broker_order_id'), table_name='ledger_events')
    op.drop_table('ledger_events')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    # ### end Alembic commands ###
